# 3. Saving Data and Models

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Loading and Saving Tensors

We can save and load a single tensor:

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
torch.save(x, 'x-file')

In [6]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

We can also save and load tensors as a list:

In [7]:
y = torch.zeros(4)
y

tensor([0., 0., 0., 0.])

In [8]:
torch.save([x, y],'x-files')

In [9]:
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

Finally, dictionary also works:

In [10]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')

In [11]:
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## Saving and Loading Models

In [23]:
class MLP(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

In [24]:
net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

Now we save the parameters:

In [25]:
torch.save(net.state_dict(), 'mlp.params')

Then, we retrieve the parameters:

In [26]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)