# 1. Data Manipulations

In [45]:
import numpy as np
import pandas as pd

import torch

## Manipulating Tensors

In [13]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
#shape of the tensor
x.shape

torch.Size([12])

In [15]:
#total number of elements
x.numel()

12

In [16]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
#reshape the tensor with 3 rows
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
#create a tensor with all zeros
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
#create a zero matrix with the same shape as x
torch.zeros_like(x)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#create a tensor with all ones
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
#create a tensor with random numbers sampled from N(0,1)
torch.randn(3,4)

tensor([[-1.8842, -0.1046,  0.8534,  0.5564],
        [-0.5882,  2.4083, -0.1769, -0.1313],
        [ 0.3285, -0.4046, -1.2212,  0.2290]])

In [29]:
#converting an array/list to tensor
x_list = [[1,2],[3,4]]
x_array = np.array([[1,2],[3,4]])
display(torch.tensor(x_list))
display(torch.tensor(x_array))

tensor([[1, 2],
        [3, 4]])

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [47]:
#clone the tensor
y = x.clone()
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])